github: Spectrasonic117
ko_fi: spectrasonic
custom:
  [
    "https://paypal.me/manuelherod?country.x=MX&locale.x=es_XC",
    "https://gitlab.com/Spectrasonic117",
    "https://spectrasonic.ml",
    "https://twitter.com/spectrasonic117",
  ]
